openapi: 3.0.3
info:
  title: traQ microservice for livekit
  version: 1.0.0
  description: トークン発行などlivekitへの橋渡しをするマイクロサービス
  contact:
    name: livekit-server
    url: 'https://github.com/pikachu0310/livekit-server'
tags:
  - name: livekit
    description: LiveKitAPI

paths:
  /ping:
    get:
      summary: サーバーの生存確認
      operationId: pingServer
      responses:
        '200':
          description: Pong
          content:
            text/plain:
              schema:
                type: string
                example: pong

  /test:
    get:
      summary: テスト用
      operationId: test
      responses:
        '200':
          description: OK

  /token:
    get:
      summary: LiveKitトークンを取得
      description: >
        指定したルームに参加するためのLiveKitトークンを取得します。
        例: `GET /token?room={UUID}`
      operationId: getLiveKitToken
      tags:
        - livekit
      parameters:
        - in: query
          name: room
          schema:
            type: string
            format: uuid
          required: true
          description: 参加するルームのUUID
      responses:
        '200':
          description: 成功 - LiveKitトークンを返します
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: LiveKit用のJWTトークン
                required:
                  - token
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /rooms:
    get:
      summary: ルームと参加者の一覧を取得
      description: >
        現在存在する(またはアクティブな)ルームと、そのルームに所属している参加者情報を取得します。
      operationId: getRooms
      tags:
        - livekit
      responses:
        '200':
          description: 成功 - ルームと参加者一覧の取得
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomWithParticipants'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

  /webhook:
    post:
      summary: LiveKit Webhook受信
      description: >
        LiveKit側で設定したWebhookから呼び出されるエンドポイントです。
        参加者の入室・退出などのイベントを受け取り、サーバ内で処理を行います。
      operationId: liveKitWebhook
      tags:
        - livekit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: LiveKit Webhook イベントのペイロード
      responses:
        '200':
          description: Webhookを正常に受信
        '400':
          description: Invalid payload
        '500':
          description: Internal Server Error

  /ws:
    get:
      summary: WebSocketエンドポイント
      description: >
        WebSocketを通じてルームの参加者一覧などをリアルタイムに受け取るためのエンドポイントです。
        入室/退出などのイベントが発生した際に、全ルームの最新状態が送信されます。
      operationId: getWs
      tags:
        - livekit
      responses:
        '101':
          description: Switching Protocols (WebSocket通信開始)
        '500':
          description: Internal Server Error

components:
  parameters:
    gameIdInPath:
      in: path
      name: gameId
      required: true
      schema:
        type: string
        format: uuid
        description: ゲームID
    termIdInPath:
      in: path
      name: termId
      required: true
      schema:
        type: string
        format: uuid
        description: タームID
    eventSlugInPath:
      in: path
      name: eventSlug
      required: true
      schema:
        type: string
        description: イベントSlug
    userIdInPath:
      in: path
      name: userId
      required: true
      schema:
        type: string
        description: ユーザーID

  schemas:
    RoomWithParticipants:
      type: object
      properties:
        roomId:
          type: string
          format: uuid
          description: ルームのID
        participants:
          type: array
          description: ルーム内の参加者一覧
          items:
            type: object
            properties:
              identity:
                type: string
                description: ユーザーIDや名前など
              joinedAt:
                type: string
                format: date-time
                description: 参加した時刻
      required:
        - roomId
        - participants
